### PR TITLE
Rust Hello World example updated

### PR DESCRIPTION
**Pull request by lucamezzalira**
*Issue #, if available:*

*Description of changes:*
I have updated different dependencies in ```cargo.toml``` and fixed the unit test that resulted broken after the dependencies update

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sriram-mv — APPROVED** [review]
Looks good overall, the gates failing seem unrelated to these changes.

**Review by torresxb1 — APPROVED** [review]

**Review by hawflau — APPROVED** [review]

**Comment by lucamezzalira** [comment]
@sriram-mv it looks like there is a post build script that fails on node (12,14,16) and graalvm, can you help fixing it?

**Comment by sriram-mv** [comment]
@hnnasit is looking into the issue on how we can get this unblocked.

**Comment by lucamezzalira** [comment]
Thanks for the update @sriram-mv 🙏

**Pull request merged**
