### PR TITLE
196 dotnet6 web backend

### PR DESCRIPTION
**Pull request by ulili5**
*Issue #196, if available:*

*Description of changes:* Adding web API backend implementation with .NET 6 Minimal API

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mzambani** [comment]
@ulili5 It is rocking! Reviewed, deployed, and tested with AWS account. Looks great!

**Comment by mingkun2020** [comment]
Thank you for your contribution! We really appreciate it. We will take time to review the pr.

**Review by jfuss — APPROVED** [review]
LGTM

**Comment by jfuss** [comment]
@ulili5 Can you handle the merge conflicts?

**Pull request merged**
