### PR TITLE
Mock S3 response for unit test

### PR DESCRIPTION
**Pull request by sleepwithcoffee**
*Issue:*  #195 

*Description of changes:*

Mock S3 response for unit testing, avoid creating S3 bucket. The current way is supposed to be integration testing rather than init testing of a code block.

### CODE REVIEW

**Comment by Beau-Gosse-dev** [comment]
Thanks @sleepwithcoffee! Is there a specific reason (like a failure) that this needs to be changed to a Mocked bucket? Or is it just preferred in this case? 

Also, we should be consistent if we do want to do this. I don't see any other uses of Moq in the templates, do we need to update .NET 6 anywhere? We should also consider being consistent with [aws-lambda-dotnet blueprints](https://github.com/aws/aws-lambda-dotnet/tree/master/Blueprints).

Lastly .NET 3.1 is End of Life and no longer getting updates. Does SAM CLI normally remove blueprints for versions that go end of life?

**Comment by Beau-Gosse-dev** [comment]
Ah, I see. So this allows the test to run in CI pipeline without any creds. Seems like a good fix.

**Comment by sleepwithcoffee** [comment]
HI @Beau-Gosse-dev , thank you for your suggestion. I take a look into [aws-lambda-dotnet blueprints](https://github.com/aws/aws-lambda-dotnet/tree/master/Blueprints) and [S3 teamplate](https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/vs2022/SimpleS3FunctionServerless/template/test/BlueprintBaseName.1.Tests/FunctionTest.cs) specifically.

I would argue that both this and that template do not perform unit testing properly, but rather integration tests. They are valid testing techniques regardless but should be applied in different stages of pipeline & deployment cycle. 

On top of that, the entry barrier for using unit testing with mocked API response is lower than with integration tests that require developers to properly set up their AWS credentials.

I recently created a PR to add S3 template for dotnet6 to SAM with the same mocking technique: https://github.com/aws/aws-sam-cli-app-templates/pull/361

I realize that dotnet3.1 runtime is coming to end of life, phase 1 to be early April. However, this change is still relevant for at least a few months.

If we agree to move on with this change, I can raise a similar PR to aws-lambda-dotnet S3 template repo.

**Review by Beau-Gosse-dev — APPROVED** [review]

**Comment by sleepwithcoffee** [comment]
hi @lucashuy @hnnasit can you review and merge this PR?

**Review by lucashuy — APPROVED** [review]
Thanks for raising this PR to mock out the S3 API calls! The changes look good to me and it looks like the CI job is passing

**Pull request merged**
