### PR TITLE
Adding a from scratch template for .net core 3.1

### PR DESCRIPTION
**Pull request by ignaciofuentes**
*Description of changes:*
Adding a from scratch template for .net core 3.1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jfuss** [comment]
@ignaciofuentes Thanks for the PR. I am having a hard time understanding what "from scratch" here means. We do have templates for .NetCore3.1 already.

**Comment by ignaciofuentes** [comment]
Hey @jfuss, the from scratch has fewer things than what we have for Hello World in .net

I saw them in NodeJS and used them as inspiration for .net.
This PR is to submit a .net equivalent to those. 

Please see.

https://github.com/aws/aws-sam-cli-app-templates/tree/master/nodejs14.x/cookiecutter-quick-start-from-scratch
https://github.com/aws/aws-sam-cli-app-templates/tree/master/nodejs10.x/cookiecutter-quick-start-from-scratch

**Comment by mndeveci** [comment]
@ignaciofuentes sorry it is been a while that we haven't responded.

Since dotnet6 is out would you mind changing this into that runtime so that more up do date version would be used?
And also, we are keeping `manifest-v2.json` file at the root of the project, which holds configuration for individual templates. Can you also update that one?

Thanks!

**Comment by hawflau** [comment]
Switching the PR to draft due to staleness. Feel free to mark it ready for review again when the change requests are addressed.

**Pull request closed without merging**
