### PR TITLE
feat: AWS Lambda Powertools for .NET templates 

### PR DESCRIPTION
**Pull request by sliedig**
*Issue #, if available:* #335

*Description of changes:*

Creating new template for runtimes `dotnet6`. These include allowing customers to selectively add AWS Lambda Powertools Tracing, Logging and Metrics utilities.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jfuss** [comment]
@sliedig Is there a reason for this still being in draft? We expect it to be moved out of draft, if we need to review.

**Comment by sliedig** [comment]
> @sliedig Is there a reason for this still being in draft? We expect it to be moved out of draft, if we need to review.

Just adding a few final changes. Also waiting to complete dotnet7. Please bear with me. Should have this done soon.

**Comment by sliedig** [comment]
@jfuss this is ready for review

**Comment by heitorlessa** [comment]
CI is failing on unit tests because the environment doesn't have `POWERTOOLS_METRICS_NAMESPACE` set - for Python, I noticed we hardcoded at runtime the name `Powertools` -- we could either do that or find a way to inject env var in the tests.

----

```bash
tests/integration/unit_test/unit_test_base.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/integration/unit_test/unit_test_base.py:169: in _test_unit_tests
    self.assertEqual(result.process.returncode, 0)
E   AssertionError: 1 != 0
----------------------------- Captured stderr call -----------------------------
Temporary directory /tmp/tmpxmzlrg0n created
Running command: sam init --no-input --location /codebuild/output/src918720838/src/github.com/aws/aws-sam-cli-app-templates/dotnet6/hello-pt --name project
PATH=/root/.pyenv/versions/3.9.16/bin:/root/.pyenv/libexec:/root/.pyenv/plugins/python-build/bin:/root/.pyenv/plugins/pyenv-virtualenv/bin:/root/.pyenv/plugins/pyenv-update/bin:/root/.pyenv/plugins/pyenv-installer/bin:/root/.pyenv/plugins/pyenv-doctor/bin:/usr/local/bin/sbt/bin:/root/.goenv/shims:/root/.goenv/bin:/go/bin:/root/.phpenv/shims:/root/.phpenv/bin:/root/.pyenv/shims:/root/.pyenv/bin:/root/.rbenv/shims:/usr/local/rbenv/bin:/usr/local/rbenv/shims:/root/.dotnet/:/root/.dotnet/tools/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tools:/usr/local/android-sdk-linux/tools:/usr/local/android-sdk-linux/tools/bin:/usr/local/android-sdk-linux/platform-tools:/codebuild/user/bin
Stdout: 
Stderr: 
['dotnet', 'test']
Running in folder /tmp/tmpxmzlrg0n/project
PATH=/root/.pyenv/versions/3.9.16/bin:/root/.pyenv/libexec:/root/.pyenv/plugins/python-build/bin:/root/.pyenv/plugins/pyenv-virtualenv/bin:/root/.pyenv/plugins/pyenv-update/bin:/root/.pyenv/plugins/pyenv-installer/bin:/root/.pyenv/plugins/pyenv-doctor/bin:/usr/local/bin/sbt/bin:/root/.goenv/shims:/root/.goenv/bin:/go/bin:/root/.phpenv/shims:/root/.phpenv/bin:/root/.pyenv/shims:/root/.pyenv/bin:/root/.rbenv/shims:/usr/local/rbenv/bin:/usr/local/rbenv/shims:/root/.dotnet/:/root/.dotnet/tools/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tools:/usr/local/android-sdk-linux/tools:/usr/local/android-sdk-linux/tools/bin:/usr/local/android-sdk-linux/platform-tools:/codebuild/user/bin
Stdout:   Determining projects to restore...
  Restored /tmp/tmpxmzlrg0n/project/src/HelloWorld/HelloWorld.csproj (in 225 ms).
  Restored /tmp/tmpxmzlrg0n/project/test/HelloWorld.Test/HelloWorld.Tests.csproj (in 260 ms).
  AspectInjector|2.8.1: Found 0 aspects, 2 injections
  HelloWorld -> /tmp/tmpxmzlrg0n/project/src/HelloWorld/bin/Debug/net6.0/HelloWorld.dll
  AspectInjector|2.8.1: Found 0 aspects, 0 injections
  HelloWorld.Tests -> /tmp/tmpxmzlrg0n/project/test/HelloWorld.Test/bin/Debug/net6.0/HelloWorld.Tests.dll
Test run for /tmp/tmpxmzlrg0n/project/test/HelloWorld.Test/bin/Debug/net6.0/HelloWorld.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed HelloWorld.Tests.FunctionTest.TestHelloWorldFunctionHandler [191 ms]
  Error Message:
   AWS.Lambda.Powertools.Metrics.SchemaValidationException : EMF schema is invalid. 'namespace' is mandatory and not specified.
  Stack Trace:
     at AWS.Lambda.Powertools.Logging.Internal.LoggingAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
   at AWS.Lambda.Powertools.Common.MethodAspectAttribute.WrapAsync[T](Func`2 target, Object[] args, AspectEventArgs eventArgs)
   at HelloWorld.Tests.FunctionTest.TestHelloWorldFunctionHandler() in /tmp/tmpxmzlrg0n/project/test/HelloWorld.Test/FunctionTest.cs:line 47
--- End of stack trace from previous location ---
```

**Comment by hnnasit** [comment]
Closing this PR as these changes have been merged in a separate PR https://github.com/aws/aws-sam-cli-app-templates/pull/350

**Pull request closed without merging**
