### PR TITLE
Added 'none' to runtime options for templates with no Lambda functions

### PR DESCRIPTION
**Pull request by rts-rob**
*Issue #, if available:*

*Description of changes:*
This pull request adds a "none" runtime template for AWS SAM applications that do not use any AWS Lambda functions. 

This PR updates and replaces #40 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jfuss** [comment]
This is a good use-case additional SAM CLI should support. However, SAM CLI also needs to be updated to support a 'none' runtime. 

@rts-rob Are you interested in contributing that as well? If not that is ok, but will close these PRs out as the examples would be unused and instead will open a Github Issue in SAM CLI to gather community feedback on the feature.

**Comment by rts-rob** [comment]
@jfuss I no longer actively use SAM so I wouldn't be the right person to contribute the `none` runtime. Community feedback approach sounds good to me!

**Comment by jfuss** [comment]
@rts-rob Sounds good. Thanks for spending the time on these. Hopefully it can be re-used in the near future.

Closing given the above conversation.

**Comment by jfuss** [comment]
For anyone you finds this and interested in the feature, I created issue for "no runtime" feature in SAM CLI: aws/aws-sam-cli#3505

**Pull request closed without merging**
