### PR TITLE
Python documentation bash scripts

### PR DESCRIPTION
**Pull request by sleepwithcoffee**
*Issue:* Since this one is minor, I didn't create an issue for this

*Description of changes:*

Changes focus on making bash scripts in Python documentation more consistent.

There are a few changes included in this PR:

1. Remove hard-coded folder names:

```bash
# Old:
my-application$ sam build

# New:
{{ cookiecutter.project_name }}$ sam build
```

3. Remove hard-coded stack name in some test scripts:

```bash
# Old:
{{ cookiecutter.project_name }}$ AWS_SAM_STACK_NAME=<stack-name> python -m pytest tests/integration -v

# New:
{{ cookiecutter.project_name }}$ AWS_SAM_STACK_NAME="{{ cookiecutter.project_name }}" python -m pytest tests/integration -v
```

4. Wrapping stack name inside double quote to prevent issue with Project Name containing whitespace:

```bash
{{ cookiecutter.project_name }}$ sam logs -n InferenceFunction --stack-name "{{ cookiecutter.project_name }}" --tail

# and
aws cloudformation delete-stack --stack-name "{{ cookiecutter.project_name }}"
```

### CODE REVIEW

**Review by jfuss — APPROVED** [review]

**Review by sriram-mv — APPROVED** [review]

**Comment by sleepwithcoffee** [comment]
since there are conflicts with recent changes, let me resolve them before merging

**Comment by lucashuy** [comment]
Hi, did you need any help resolving the conflicts?

**Comment by sleepwithcoffee** [comment]
Hi @lucashuy, I was a bit busy for the last few weeks so there was a bit of a delay. However, I added in another new change to enhance the documentation with bash scripts.
I separated into a different PR for Python 3.7 here for easier tracking and reviewing since this PR turns out to be quite large: https://github.com/aws/aws-sam-cli-app-templates/pull/406

**Comment by hnnasit** [comment]
Closing this PR as the changes have been merged with the separate PRs created. Thanks for all the contributions @sleepwithcoffee!

**Pull request closed without merging**
